import Image from 'next/image'
import Link from 'next/link'
import { UseTermsAndConditionsDataType } from 'views/User/TermsAndConditionsPage/types'
import ProjectLogo from 'assets/images/images/project-logo.png'
import {
  ModalContainer,
  LogoContainer,
  ModalContent,
  TermsContainer,
  TermsSubtitleContainer,
  CheckboxContainer,
  CheckboxContent,
  ChecboxTextContainer
} from '@/styles/Views/User/TermsAndConditionsPage/ModalView/Modal'

const Modal = ({
  termsandConditionsData
}: {
  termsandConditionsData: UseTermsAndConditionsDataType
}) => {
  return (
    <ModalContainer>
      <LogoContainer>
        <Link href="/">
          <Image src={ProjectLogo} alt="Asic mining" />
        </Link>
      </LogoContainer>
      <ModalContent>
        <TermsContainer>
          Terms & Conditions
          <TermsSubtitleContainer>
            <h3 style={{ color: '#748cbf' }}>
              Terms of Use and Hosting Service Agreement
            </h3>
            <p>
              These Terms of Use (“the Terms”) and the Hosting Service Agreement
              (“the Agreement”) set forth the legally binding terms for you
              (“the User”) in the event you engage Basic Partners LLC (“the
              Company”), d.b.a Basic Mining, in Bitcoin mining services to
              include hardware sales, hosting, and participation in the Basic
              Mining Marketplace (“the Marketplace”). By accessing the
              Marketplace and using Basic Mining services, you are accepting
              these Terms and the conditions of the Hosting Services Agreement
              and you represent and warrant that you have the right, authority,
              and capacity to enter into these Terms and Agreement.
            </p>
            <h2 className="term">I. Marketplace Terms of Use</h2>
            <b>1. MARKETPLACE</b>
            <p>
              <u>b. Marketplace Services:</u>The Basic Mining Marketplace (“the
              Marketplace”) is a platform that allows Users to buy, sell, and
              trade their Assets managed by the Company. These Assets include
              hosted and non hosted hardware. Hosted hardware listed in the “Buy
              & Host” section of the Marketplace include the hardware and
              managed Hosting Services as defined under Section II of the
              Agreement. Non hosted hardware listed in the “Shop” section of the
              Marketplace include only hardware and shipping, Hosting Services
              are not provided under this type of listing.
            </p>
            <p>
              Assets can be sold under an Auction style listing, or set for Sale
              at a desired asking price. Auction listings include an asking
              price and have a set expiration for when the auction ends. Sellers
              of an auction listing are not guaranteed a sale, nor a bid for the
              full asking price of their assets. Buyers are not guaranteed to
              win an auction if they are the highest bidder. The Seller has a
              right to choose the Buyer of their listed product during the
              bidding process.
            </p>
            <p>
              <u>c. Seller Obligations:</u> As a Seller in the Marketplace you
              guarantee the delivery of the Asset listed for sale. The Seller of
              a successful transaction will pay the Company a commission fee of
              5% of the Total Asking Price of the Asset sold. This commission
              fee will be paid out of the sales proceeds generated by the sale
              of the Asset after the Buyer has successfully remitted payment in
              full.
            </p>
            <p>
              <u>d. Buyer Obligations:</u> As a Buyer in the Marketplace you
              guarantee payment in full of an auction bid and, or the purchase
              of an Asset. Failure to provide payment within 24 hours of a
              purchase, or won auction will result in forfeiture of your right
              to acquire that Asset. Failure to meet the Buyer’s obligations can
              result in removal from the Marketplace platform.
            </p>
            <p>
              <u>e. Platform’s Roles:</u> The Marketplace acts as an
              intermediary, facilitating transactions between Sellers and
              Buyers. As such, the Marketplace ensures Sellers deliver sold
              Assets to the Buyer after the Buyer has successfully remitted
              payment in full. The Marketplace does not guarantee a sale from an
              Asset listing, nor payment from the Buyer of a listing.
            </p>
            <p>
              <u>f. Payment Terms:</u> Acceptable forms of payment include ACH,
              Wire Transfer or cryptocurrency as the Company designates from
              time to time. If User elects to pay with cryptocurrency, User
              shall coordinate with the Company to facilitate this transaction.
              A processing fee may apply to cryptocurrency payments.
            </p>
            <p>
              <u>f. Disputes and Refunds:</u> All sales are final and products
              are sold as is.
            </p>
            <p>
              <u>g. Governing Law:</u> All claims arising out of or related to
              these Terms are governed by and construed in accordance with the
              laws of the State of Wyoming without giving effect to any choice
              or conflict of law provision or rule that would cause the
              application of the laws of any jurisdiction other than the State
              of Wyoming.
            </p>
            <h2 className="term">II. Hosting Service Agreement</h2>
            <b>1. HOSTING SERVICE</b>
            <p>
              <u>a. Service Arrangement:</u> The Company shall provide a managed
              Hosting Service as stated in the site specific Service Order
              (“Service”).
              <br />
              <br />
              i. “Hosting Service” is defined as hosting of the hardware
              belonging to the User and specified in the Service Order (“User
              Hardware”) at a data center owned, leased, operated, or reserved
              by the Company (“Hosting Facility”) selected by User. As part of
              the Hosting Service, the company shall provide for or arrange
              shelf and/or rack space, sufficient electrical capacity at the
              required voltage and wattage, provision of electricity, monitoring
              and services (according to section 3(b)) of User Hardware to
              achieve the Service Level as defined in the Service Order. The
              Company reserves the right to switch the Hosting Facility to a
              like facility that is in the same region and at a cost that is
              equal to or less than the Service Fee. The Company reserves the
              right to provide the Hosting Service directly or through agents,
              vendors and qualified third parties.
            </p>
            <p>
              <u>b. Service Level:</u> The Company shall use commercially
              reasonable efforts to make the Service available to the User
              greater than or equal to ninety five percent (95%) of the time
              each month (the “Service Level”), except in the event of
              maintenance of the Hosting Facility and its associated
              infrastructure, User Hardware failure, or Force Majeure Events.
              The Company does not guarantee that the Service will not be
              interrupted by outages or shortages of power which are planned or
              unplanned and outside of the Company’s control, and the Company
              will not be liable for the foregoing. The Company does not
              guarantee the supply of electricity during the winter and peak
              hours of the day and the User acknowledges that there is a
              possibility of voluntary or involuntary downtime, curtailment by
              the Company or the energy provider, or outages or shortages of
              power of no more than 600 hours in a calendar year
            </p>
            <p>
              <u>c. Service Order:</u> The User acknowledges and agrees that
              certain terms of the Service Order, including the Service
              Arrangement, the estimated Commencement Date, the User Hardware,
              the Facilities, Service Rate, the Service Term and Termination,
              the Deposit, as well as other related charges are as specified in
              Service Order hereto. The Service Order shall be deemed to be
              agreed by the User through the duly executed copy of this
              Agreement and an accompanying Service Order by the authorized
              representative of each party.
            </p>
            <p>
              <u>c. Membership Program:</u> By purchasing hosted hardware from
              The Marketplace, or hosting any hardware at one of the Company’s
              Hosting Facilities, the User automatically opts into the Basic
              Mining’s Membership program. The details of the Membership program
              can be found at basicmining.com/hosting.
            </p>
            <b>2. USER HARDWARE AND DELIVERY</b>
            <p>
              <u>a. Delivery to Facilities:</u> User Hardware may require
              shipping and delivery to the Facility from the hardware
              manufacturer or a third-party distributor or reseller. In such
              cases, the Company shall allow for the delivery of the User
              Hardware to the appropriate Facility contained in the Service
              Order, and shall make reasonable efforts to ensure operation by
              the estimated on-line date. The Company shall provide storage for
              User Hardware after delivery under terms specified in the Service
              Order.
            </p>
            <p>
              <u>b. Inspection and Installation:</u> The Company shall inspect
              the User Hardware for suitability of operation and has full
              discretion to accept or reject any User Hardware. Upon receipt,
              inspection, and confirmation that User Hardware is fully
              functioning, the Company shall provide for the installation of
              User Hardware at the applicable Facility. The Company shall charge
              a setup fee to the User in accordance with the Service Order. If
              the Company determines, in its sole discretion, that User Hardware
              is unsuitable, the Company shall pack for shipment and notify User
              of the unsuitability. User Hardware suitability shall be
              determined based on safety, physical condition, age and
              modifications from factory configuration. User shall be
              responsible for all costs to be incurred by the Company in the
              connection with the return of any unsuitable User Hardware, and
              User agrees to pay any such amounts to the Company prior to the
              return of the unsuitable User Hardware. Storage fees in accordance
              with the Service Order shall commence 15 days after such
              notification to the User of the unsuitability of any portion of
              the User Hardware.
            </p>
            <p>
              <u>c. Operation and Start Date: </u> The Company shall make
              commercially reasonable efforts to commence operation of User
              Hardware on the scheduled Service commencement date reflected in
              the Service Order; provided, however, that the Company shall not
              be responsible for any delay in operation of User Hardware for any
              reason, including delay in receipt of User Hardware, Force Majeure
              Events, lack of available rack space, a Facility’s electrical or
              network connectivity problems, or loss of power due to the
              Transmission/Distribution network. Storage fees are not applicable
              for suitable User Hardware pending installation. In the event the
              Company is unable to commence operation of a subset or tranche of
              User Hardware within 90 days of the estimated Commencement Date,
              User may remove from this agreement the subset or tranche of User
              Hardware impacted by the delay via written notice to the Company
              and arrange for the transportation of User Hardware from the
              Facilities at User’s expense.
            </p>
            <p>
              <u>d. Serial Numbers:</u> The Company shall provide User with the
              serial number(s) for each machine included as part of User
              Hardware within 20 business days of service commencement.
            </p>
            <b>3. MAINTENANCE AND REPAIRS</b>
            <p>
              <u>a. Facility Maintenance: </u> The Company and its affiliates of
              the Facility shall be entitled to perform maintenance and any
              actions as deemed necessary or desirable by the Company or its
              agents with respect to a Facility and to maintain the network.
              User acknowledges and agrees that performance of such maintenance
              may cause the network to be temporarily inaccessible and the User
              Hardware may experience temporary down time or unavailability. The
              Company shall cause its Facilities to use commercially reasonable
              efforts to conduct such Maintenance in a manner to avoid or
              minimize the unavailability of the Service. If scheduled
              Maintenance is expected to interrupt the availability of Service,
              the Company may give User notice, by means of electronic
              communication, prior to conducting such Maintenance, identifying
              the time and anticipated duration. Planned service interruptions
              do not accrue toward the 95% uptime service level target.
            </p>
            <p>
              <u>b. User Hardware Maintenance and Repair: </u> The Company shall
              be entitled to perform maintenance and any actions as deemed
              necessary or desirable with respect to User Hardware and charge
              User the Repair Fee listed on the Service Order. In the event that
              the User Hardware fails, the User will be notified of an estimated
              cost and timeline for User Hardware repairs to be completed. The
              Company shall use commercially reasonable efforts to repair User
              Hardware on-site but may require User Hardware to be transported
              to a repair shop or shipped to the manufacturer for critical
              repairs. User Hardware sent to the manufacturer for repair may be
              fully covered under a standard manufacturer warranty, but shipping
              costs will be paid by the User to the Company within three (3)
              business days of written notification by the Company; provided
              that if the standard manufacturer warranty does not cover any
              portion of such repairs, User will be responsible for any
              uncovered costs related to such repairs. Users may elect, at
              User’s option, to select the third-party repair location. If the
              User does not agree with repair options or costs, the User has the
              right to cancel this Agreement as to the affected User Hardware
              and have the affected User Hardware shipped at User’s expense in
              accordance with the Service Order. If User does not respond to
              options for repair provided by the Company within fifteen (15)
              days, the Company reserves the right to cancel the Agreement as to
              the affected User Hardware and charge the storage fees in
              accordance with the Service Order.
            </p>
            <b>4. SERVICE FEE AND User RESPONSIBILITY</b>
            <p>
              <u>a. Delivery and Installation of User Hardware:</u>Any costs for
              the installation and mounting of User Hardware shall be contained
              in the Service Order. User shall pay all tariffs, taxes, shipping
              costs, or other expenses associated with shipping, importing,
              exporting, and transporting User Hardware to the applicable
              Facility.
            </p>
            <p>
              <u>b. Private Key and Wallet Security:</u> User shall at all times
              be responsible for maintaining software and all other
              telecommunications, internet access and related equipment required
              to receive User’s digital asset, cryptocurrency, virtual currency,
              digital currency, or digital commodity (e.g., Bitcoin and
              Ethereum) produced by the proof-of-work cryptographic protocol of
              a computer network and generated by User’s use of User Hardware
              (“Mining Rewards”). User is solely responsible for the security of
              User’s private keys. User shall hold the Company harmless from
              user or access security with respect to any of User Hardware or
              the applicable Facility. The Company does not provide any service
              to detect or identify any security breach of User Hardware or the
              Facilities. The Company does not provide any tests employing tools
              and techniques intended to gain unauthorized access to User
              Hardware or User’s personal property.
            </p>
            <p>
              <u>c. Basic Mining Account Security: </u> User shall maintain the
              security of passwords for its Basic Mining account. User shall
              notify the Company if User suspects its Basic Mining account has
              been hacked, stolen, accessed without authorization, or otherwise
              compromised. If the Company suspects any security violations have
              occurred related to User’s Basic Mining account, the Company may
              suspend access to User’s account and User Hardware pending
              resolution.
            </p>
            <p>
              <u>d. Maintenance:</u> The User may be required to purchase from
              the Company other equipment, accessories, software, or hardware,
              such as power cords, to ensure compliance with the technical and
              fire safety norms at the applicable Facility (“Required
              Purchase”). The User shall be notified about and approve of any
              Required Purchase in advance. If User does not approve a Required
              Purchase within fifteen (15) days of being notified of such
              Required Purchase, the Company may terminate the Agreement as to
              the affected User Hardware and have the affected User Hardware
              shipped to User at User’s expense.
            </p>
            <p>
              <u>e. Return of User Hardware:</u> The User may request upon the
              expiration or termination of this Agreement, for the Company to
              return any and all User Hardware, unless User is in default of
              payment. The Company shall charge a fee for the tear down,
              storage, and return of User Hardware as listed on the Service
              Order. All additional fees, taxes and handling costs and risk of
              loss during shipping shall be borne by the User. If the User does
              not provide written return directions within fifteen (15) days of
              termination or expiration of this Agreement, the Company shall be
              entitled to dispose of the User Hardware. The Company will not be
              responsible for any damage or operation deficiency of User
              Hardware and the Company will not repair or reimburse User in any
              form.
            </p>
            <b>5. PAYMENT TERMS AND TAXES</b>
            <p>
              <u>a. Service Fee:</u> The Company will bill recurring monthly
              charges in arrears. The Service Fee is calculated based on the
              actual power consumption of User Hardware as measured by the
              Company. The Company will invoice the User for the total monthly
              fees for the prior month for use of the Service (“Service Fee”) no
              later than the 10th date of each month for the prior month. Labor,
              shipping, storage and materials will be billed as required and are
              due upon receipt. Fees not disputed by User within thirty (30)
              days of payment or due date are conclusively deemed accurate.
            </p>
            <p>
              <u>b. Payment Terms:</u> Acceptable forms of payment include ACH,
              Wire Transfer or cryptocurrency as the Company designates from
              time to time. Payments of Service Fee for the prior month will be
              due on or before the 10th of each month. If User elects to pay
              with cryptocurrency, User shall deliver the designated
              cryptocurrency in the amount equal to the invoice due amount into
              the Company’s digital wallet by 5:00 p.m. (Central Standard Time)
              on the 10th date of the same month.
            </p>
            <p>
              <u>c. Deposit:</u>The User shall deliver to the Company a deposit
              equal to the amount stated in the Service Order (“Deposit”). If
              User fails to pay any Service Fee, the Company may use, apply or
              retain all or any portion of the Deposit for the payment of any
              amount due or to reimburse or compensate the Company for any
              liability, expenses, loss or damages which the Company may suffer
              or incur by reason thereof. If the Company uses or applies all or
              any portion of the Deposit, User shall within ten (10) days after
              written request thereof deposit money with the Company sufficient
              to restore the Deposit to the full amount required by this
              Agreement. Within sixty (60) days after the expiration or
              termination of this Agreement, unless the Company elects to apply
              Deposit to unpaid Service Fees, the Company will return the
              portion of the Deposit not used or applied. No part of the Deposit
              shall be considered to be held in trust, to bear interest or to be
              prepayment for any Service Fee to be paid by User under this
              Agreement.
            </p>
            <p>
              <u>d. Nonpayment:</u> For overdue invoices, the Company shall
              utilize the User Deposit to pay an unpaid balance due. The User
              shall be required to restore the Deposit and pay any balance due
              within ten (10) days of written notice. In the event the Deposit
              is not restored within the specified time, the Company may turn
              off User Hardware, disable User’s access to accounts, remove from
              the rack, and/or reconfigure User Hardware for the Company’s use.
              User Hardware may be removed from the rack, thus terminating the
              Service, and requiring the payment of tear down and storage fees
              in accordance with the Service Order. If the Service Agreement is
              terminated, the Company and User may enter into a new Service
              Agreement, which would require new Set Up Fees.
            </p>
            <p>
              <u>e. Service Fee Adjustment: </u> The Company reserves the right
              to provide written notice to modify its rates upon a material,
              demonstrable increase in any of the Company’s operating costs,
              including without limitation, power rates, leasing rates, tax
              rates and/or increased regulatory compliance costs. Upon receipt
              of a notice of rate increase, User may within thirty (30) days
              thereafter elect to terminate the Service by providing the Company
              with a notice of termination that will occur no sooner than thirty
              (30) days prior to the effective date of the rate increase.
            </p>
            <b>6. TERM, TERMINATION, MODIFICATION AND SUSPENSION </b>
            <p>
              <u>a. Term:</u> Unless terminated sooner as provided in this
              Agreement or otherwise stated in the Service Order, the initial
              term of the Services provided under this Agreement shall begin on
              the Service Order Commencement Date and expire five (3) years
              thereafter (the “Initial Term”). Upon expiration of the Initial
              Term, this Agreement will renew automatically for additional one
              (1) year terms (each, a “Renewal Term”, and together with the
              Initial Term, “Term”) unless either party provides written notice
              to the other party of its desire to avoid the Renewal Term at
              least one hundred eighty (180) days in advance of the conclusion
              of the then current Term.
            </p>
            <p>
              <u>b. Termination:</u> The Company may terminate this Agreement
              for cause immediately following written notice if User: (i) fails
              to make any payments, after notice an opportunity to cure, due
              pursuant to this Agreement; (ii) violates, or fails to perform or
              fulfill any covenant or provision of this Agreement, and such
              breach is not cured within thirty (30) days after notification
              from the Company; (iii) enters into bankruptcy or insolvency; or
              (iv) enters into an agreement for the sale of all or substantially
              all of its assets or attempts to transfer, by sale of its
              securities, merger or any other means, at least 50% of its capital
              stock. Without limiting the foregoing, the Company may terminate
              or suspend all or a portion of the Services or otherwise terminate
              any existing Service Order if necessary to be in compliance with
              applicable law, rules, regulations, administrative or judicial
              orders or decree. The Company shall notify User in writing of such
              suspension or termination, which shall be effective as of the date
              of receipt transmittal of such written notice. The parties agree
              that they will have no liability whatsoever to the other for any
              damage, loss, expense or cost as a result of such termination or
              suspension. Further, the Company may terminate the Agreement for
              convenience by providing User with a one hundred eighty (180) day
              written notice.
            </p>
            <p>
              <u>c. Effects of Termination:</u> Upon termination or expiration
              of this Agreement, User agrees to immediately pay to the Company
              all amounts then owed. The Company will provide written notice of
              the total funds owed within five (5) days of such termination or
              expiration. If User fails to make such payments within ten (10)
              days, the Company shall have the right to (i) sell or retain
              possession of; (ii) reconfigure for the Company’s use, or (iii)
              remove and store at User’s expense, all or any portion of User
              Hardware without any costs, obligation or liability by the
              Company. Any of the measures above can be used to recover User
              funds owed plus reasonable costs (including attorney’s fees) to
              facilitate the recovery of funds owed by User. The Company will
              provide detailed reporting of any measures taken to recover funds
              owed. If the Company recovers the User balance as a result of the
              sale of the User Hardware, the Company will return any additional
              funds in excess of what is owed by the User (including the costs
              associated with such collection) within 30 days. Upon the
              termination of the Agreement for any reason, the Company will
              permanently delete User’s personal information from any and all
              storage devices.
            </p>
            <b>7. SECURITY INTEREST </b>
            <p>
              User hereby grants the Company a security interest in all User
              hardware in the Company’s possession, now or at any time
              hereafter, in order to secure the timely performance of this
              agreement by User and secure the payment of all invoices, charges
              and costs. Furthermore, the User grants the Company a security
              interest in all User hardware for the payment of engineering work,
              labor, or other charges that are due and unpaid by User.
              Furthermore, the User authorizes the Company to file at any time
              and from time to time any financing statements describing the User
              hardware, including a UCC financing statement naming User as
              debtor and the Company as secured party with respect to the User
              hardware with the applicable secretary of state. User further
              agrees to take such actions as are reasonably necessary to
              effectuate the foregoing and to permit the Company to exercise any
              of its rights and remedies hereunder.
            </p>
            <b>8. REPRESENTATIONS AND WARRANTIES </b>
            <p>
              <u>a. Authority and Capacity: </u> Each party represents,
              warrants, and covenants that (i) it has full legal capacity,
              right, power and authority to execute and perform its obligations
              under this Agreement; and (ii) its performance of obligations
              hereunder will not violate any applicable laws or require the
              consent of any third party.
            </p>
            <p>
              <u>b. Title to User Hardware and Receipt of Mining Rewards:</u>{' '}
              User represents, warrants, and covenants that (i) User has clear
              title, free and clear of all security interests or liens, to User
              Hardware, including the legal right to use, operate, and locate
              the User Hardware; and (ii) its receipt of Mining Rewards will not
              violate any applicable laws or require the consent of any third
              party.
            </p>
            <p>
              <u>c. Accuracy of User Information:</u> User represents and
              warrants that: (i) the information User has provided for the
              purpose of establishing an account with the Company is true,
              accurate, current and complete; and (ii) the User will maintain
              and promptly amend all information and material to keep it true,
              accurate, current and complete.
            </p>
            <p>
              <u>d. FCPA; Anti-Bribery:</u> In carrying out its responsibilities
              hereunder, each Party represents that it shall comply with all
              applicable anti-bribery laws including, but not limited to, the
              U.S. Foreign Corrupt Practices Act, as revised (“FCPA”), and the
              Organization for Economic Cooperation and Development Anti-Bribery
              Convention, as implemented in the territory. Each Party represents
              that it understands that the FCPA generally prohibits the promise,
              payment, or giving of anything of value either directly or
              indirectly to any government official for the purpose of obtaining
              or retaining business or any improper advantage. For purposes of
              this section, “government official” means any official, officer,
              representative, or employee of any non-U.S. government department,
              agency or instrumentality (including any government-owned or
              controlled commercial enterprise), or any official of a public
              international organization or political party or candidate for
              political office. Each Party represents and warrants unto itself
              that, in the performance of this Agreement, (i) neither it nor any
              of its representatives are governmental employees or officials or
              candidates for political office and it will advise the other Party
              of any change in such representation; (ii) it and its
              representatives have not and will not make, offer, or agree to
              offer anything of value to any government official, political
              party, or candidate for office; (iii) it will comply with all
              provisions of the FCPA and the regulations thereunder as amended
              from time to time; and (iv) it agrees to indemnify, defend, and
              hold the other Party harmless for damages and expenses resulting
              from a violation of the foregoing by itself or its
              representatives.
            </p>
            <p>
              <u>e. Compliance with Laws:</u> The User represents and warrants
              that: (i) the User will not use the Service for the development,
              design, manufacture, production, stockpiling, or use of nuclear,
              chemical or biological weapons, weapons of mass destruction, or
              missiles, in a country listed in Country Groups D:4 and D:3, as
              set forth in Supplement No. 1 to Part 740 of the United States
              Export Administration Regulations, (ii) the User shall not provide
              administrative access to the Service to any person (including any
              natural person or government or private entity) that is located in
              or is a national of any embargoed or highly restricted country
              under United States export regulations, which include Cuba, Iran,
              and Sudan, and (iii) User are not on the United States Department
              of Treasury, Office of Foreign Asset Controls list of Specially
              Designated Nationals and Blocked Persons.
            </p>
            <p>
              f. The Company represents that it has no knowledge, or reason to
              know, of any issues that would render any Facility unfit for
              cryptocurrency mining operations.
            </p>
            <p>
              g. The Company agrees that in the event it enters into any
              financing, it shall not allow User owned fixtures or equipment to
              be collateralized or provided as a guarantee for said financing.
            </p>
            <b>9. RISK FACTORS AND LIMITATIONS OF LIABILITY </b>
            <p>
              <u>a. Protocol Risk:</u> The Company does not own or control the
              underlying software cryptographic protocols of networks which
              govern the operation of any cryptocurrency. The Company is not
              responsible for the operation of the underlying protocols, and
              makes no representation or guarantee regarding their security,
              functionality, or availability.
            </p>
            <p>
              <u>b. Network and Information Security Risk: </u> The User
              acknowledges and agrees that the use of telecommunications and
              data communications networks and the internet may not be secure
              and that connection to and transmission of data and information
              over the internet and such facilities provide the opportunity for
              unauthorized access to wallets, computer systems, networks and all
              data stored herein. Information and data transmitted through the
              internet or stored on any equipment through which internet
              information is transmitted may not remain confidential and the
              Company does not make any representation or warranty regarding
              privacy, security, authenticity, and non-corruption or destruction
              of any such information. The Company does not warrant that the
              Service or User’s use will be uninterrupted, error-free, or
              secure. The Company shall not be responsible for any adverse
              consequence or loss whatsoever to User’s use of the Service or the
              internet. Use of any information transmitted or obtained by User
              from the Company is at User’s own risk. The Company is not
              responsible for the accuracy or quality of information obtained
              through its network, including as a result of failure of
              performance, error, omission, interruption, corruption, deletion,
              detect, delay in operation or transmission, computer virus,
              communication line failure, theft or destruction or unauthorized
              access to, alteration of, or use of information or facilities, or
              malfunctioning of websites. The Company does not control the
              transmission, computer virus, communication line failure, theft or
              destruction or unauthorized access to, alteration of, or use of
              information or facilities, or malfunctioning of websites.
            </p>
            <p>
              <u>c. As Is and No Warranty:</u> THE COMPANY MAKES NO WARRANTIES
              OR GUARANTEES RELATED TO THE AVAILABILITY OF SERVICE OR THE
              OPERATING TEMPERATURE OF THE DATA CENTER. THE SERVICE AND THE DATA
              CENTER PROVIDED BY THE COMPANY ARE PROVIDED “AS IS”. User
              ACKNOWLEDGES THAT THE COMPANY DOES NOT PROVIDE MECHANICAL COOLING
              OR BACKUP POWER AND THE DATA CENTER IS SUBJECT TO SWINGS IN LOCAL
              TEMPERATURE, WIND, HUMIDITY, ETC. THE COMPANY MAKES NO WARRANTY
              WHATSOEVER, INCLUDING ANY (I) WARRANTY OF MERCHANTABILITY; (II)
              WARRANTY OF FITNESS FOR A PARTICULAR PURPOSE; (III) WARRANTY
              AGAINST INTERFERENCE; OR (IV) WARRANTY RELATED TO PRICE OR
              LIQUIDITY OF ANY DIGITAL ASSET. THE COMPANY DOES NOT WARRANT THAT
              (X) THE SERVICE SHALL BE AVAILABLE 24/7 OR FREE FROM MINOR
              INTERRUPTIONS; (Y) THE SERVICE SHALL MEET User’S REQUIREMENTS
              OTHER THAN AS SET OUT IN THE WRITTEN AGREEMENT BETWEEN THE
              PARTIES; (Z) THE SERVICE SHALL PROVIDE ANY FUNCTION NOT DESIGNATED
              IN THE WRITTEN AGREEMENT BETWEEN THE PARTIES.
            </p>
            <p>
              <u>d. LIMITATION OF LIABILITY:</u> NOTWITHSTANDING ANYTHING TO THE
              CONTRARY IN THIS AGREEMENT, IN NO EVENT WILL EITHER PARTY BE
              LIABLE TO THE OTHER PARTY FOR (I) LOST PROFITS; (II) LOSS OF
              BUSINESS; (III) LOSS OF REVENUES; (IV) LOSS, INTERRUPTION OR USE
              OF DATA OR LOSS OF USE OF User HARDWARE; (V) ANY CONSEQUENTIAL OR
              INDIRECT DAMAGES; OR (VI) COST OF COVER, ANY INCIDENTAL, SPECIAL,
              RELIANCE, EXEMPLARY OR PUNITIVE DAMAGES (IF APPLICABLE), EVEN IF
              ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, EXCEPT TO THE EXTENT
              THAT ANY SUCH LOSS OR DAMAGES ARISES OUT OF THE OTHER PARTY’S
              GROSS NEGLIGENCE, BAD FAITH OR WILLFUL MISCONDUCT. THE LIMITATIONS
              SET FORTH HEREUNDER WILL APPLY TO ALL CLAIMS AND CAUSES OF ACTION,
              REGARDLESS OF WHETHER IN CONTRACT, TORT, STRICT LIABILITY OR OTHER
              THEORY.
            </p>
            <p>
              <u>e. Indemnification:</u> The User agrees to indemnify, defend
              and hold harmless the Company and its officers, managers,
              partners, members, agents, employees, affiliates, attorneys,
              heirs, successors and assigns from any and all claims, demands,
              actions, suits, proceedings, damages, judgments, liabilities,
              losses and expenses, including without limitation, attorney’s fees
              (“Losses”) arising from or in connection with (i) any legal,
              regulatory or governmental action against or including User; (ii)
              the maintenance or operation of User Hardware; (iii) any Loss by
              any of User, User’s officers, managers, partners, members; and
              (iv) any breach or nonperformance by User of any provision or
              covenants set forth in this Agreement or the Service Order;
              provided, however, that User shall not have any liability with
              respect to Losses finally determined by a court of competent
              jurisdiction to result from the Company’s fraud, gross negligence
              or willful misconduct.
            </p>
            <b>10. CONFIDENTIALITY </b>
            <p>
              <u>a. General:</u> Each party acknowledges that it and its
              employees or agents may, in the course of performing its
              responsibilities under this Agreement, be exposed to or acquire
              information which is Confidential Information of the other party.
              The term “Confidential Information” refers to confidential or
              proprietary information of a party including, without limitation,
              business plans, strategies, forecasts and projections and
              information about business structures, operations, systems,
              finances, assets, investments, investment strategies, software and
              other technology systems, and personnel, Users and suppliers.
              Confidential Information does not include if it (i) is known to
              the receiving party prior to receipt from the disclosing party
              directly or indirectly from a source other than one having an
              obligation of confidentiality to the disclosing party; (ii)
              becomes known (independently of disclosure by the disclosing
              party) to the receiving party directly or indirectly from a source
              other than one having an obligation of confidentiality to the
              disclosing party; (iii) becomes publicly known or otherwise ceases
              to be confidential, except through a breach of this Agreement by
              the receiving party; or (iv) is independently developed by the
              receiving party.
            </p>
            <p>
              <u>b. Inducement to Leave Employment: </u> The Company and User,
              and their respective employees, owners, agents, and officers,
              agree that during the term of the Agreement and for the period of
              12 months following termination of this Agreement (howsoever
              arising) not to directly or indirectly, and whether for themselves
              or for the benefit of any other person, induce or endeavor to
              induce any officer or employee of the other to leave his or her
              employment.
            </p>
            <p>
              <u>c. Limited Use and Disclosure:</u> Neither party may use nor
              copy any Confidential Information except to the limited extent
              necessary to perform its obligations under this Agreement and will
              not disclose any Confidential Information to any person or entity
              other than to its employees who have a need to know the
              Confidential Information or as otherwise expressly permitted by
              this Agreement. Each party shall use the same measures that it
              uses to protect its own most confidential and proprietary
              information to protect the Confidential Information, but in no
              event less than commercially reasonable measures.
            </p>
            <p>
              <u>d. Return of Confidential Information:</u> Upon termination or
              expiration of this Agreement, or at any other time at the request
              of the other party, each party shall return to the other party, or
              destroy and delete, as applicable, all Confidential Information
              and any copies thereof in its possession or control.
            </p>
            <p>
              <u>e. Privacy:</u> The Company shall comply with all applicable
              privacy laws throughout the Term, and will take all commercially
              reasonable steps within the Company’s power to ensure that the
              Company’s employees, contractors and other Users comply with all
              applicable privacy laws.
            </p>
            <p>
              <u>f. Basic Mining Proprietary Information:</u> Except for the
              rights expressly granted herein, all rights, titles, and interests
              to any and all User relationships, proprietary rights and
              intellectual property rights in the Company’s data will remain
              with and be the exclusive property of the Company.
            </p>
            <p>
              <u>g. Government Enquiries and Investigations: </u> The Company
              may cooperate with any government or legal investigation regarding
              any aspect of the Service, which may include producing identifying
              information of User.
            </p>
            <p>
              <u>h. Acknowledgement:</u> The parties acknowledge that the
              provisions set forth in this Section 10 are reasonable in scope
              and duration and are not unduly restrictive.
            </p>
            <b>11. INTELLECTUAL PROPERTY</b>
            <p>
              Neither party may use the other party’s trademarks, service marks,
              trade names, copyrights, other intellectual property rights or
              other designations in any promotion, publication or press release
              without the prior written consent of the other party in each case,
              whose consent shall not be unreasonably withheld.
            </p>
            <b>12. INSURANCE </b>
            <p>
              The Parties agree that the Company is not an insurer and the User
              Hardware is not covered by any insurance policy held by the
              Company. The User will be solely responsible to insure their
              equipment and property against all forms of damage. The User shall
              further carry liability insurance in the event that User Hardware
              were to damage the Company’s or its other User’s property. If User
              does not insure the User Hardware, User will do so at User’s sole
              risk. No claim shall be brought against the Company for any loss
              suffered by User for loss of units, property, or revenues, except
              arising out of the Company’s gross negligence or willful
              misconduct.
            </p>
            <b>13. DISPUTES </b>
            <p>
              To the fullest extent permitted by law, the parties hereto (the
              “Parties”) agree to waive their rights to seek remedies in court,
              including but not limited to rights to a trial by jury. The
              Parties agree that any dispute between or among them or their
              subsidiaries, affiliates or related entities arising out of,
              relating to or in connection with this Agreement, will be resolved
              in accordance with a confidential two-step dispute resolution
              procedure involving: (1) non-binding mediation, and (2) binding
              arbitration under the Federal Arbitration Act, 9 U.S.C. 1, et.
              seq., or state law, whichever is applicable. Any such mediation or
              arbitration hereunder will be under the auspices of the American
              Arbitration Association (“AAA”) pursuant to its then current
              Commercial Arbitration Rules and Mediation Procedures (the “AAA
              Commercial Rules”). No arbitration will be initiated or take place
              with respect to a given dispute if the Parties have successfully
              achieved a mutually agreed to resolution of the dispute as a
              result of the step-one mediation. The arbitration (if the dispute
              is not resolved by mediation) will be conducted by a single AAA
              arbitrator, mutually selected by the Parties, as provided for by
              the AAA Commercial Rules. The Parties agree that the arbitrator
              will apply the substantive law of the State of Wyoming to all
              state law claims and federal law to any federal law claims, that
              discovery will be conducted in accordance with the AAA Commercial
              Rules or as otherwise permitted by law as determined by the
              arbitrator. In accordance with the AAA Commercial Rules (a copy of
              which is available through AAA’s website, www.adr.org), the
              arbitrator’s award will consist of a written statement as to the
              disposition of each claim and the relief, if any, awarded on each
              claim. The Parties understand that the right to appeal or to seek
              modification of any ruling or award by the arbitrator is limited
              under state and federal law. Any award rendered by the arbitrator
              will be final and binding, and judgment may be entered on it in
              any court of competent jurisdiction. Nothing contained herein will
              restrict either party from seeking temporary injunctive relief in
              a court of law. In the event AAA refuses to accept jurisdiction
              over a dispute, the Parties agree to submit to
              Judicial-Arbitration-Mediation Services (“JAMS”) mediation and
              arbitration applying the JAMS equivalent of the AAA Commercial
              Rules. If AAA and JAMS refuse to accept jurisdiction, the Parties
              may litigate solely and exclusively in the State of Wyoming.
            </p>
            <b>14. GENERAL PROVISIONS </b>
            <p>
              <u>a. Captions and Section Headings:</u> Captions and section
              headings are for convenience only, are not a part of this
              Agreement and may not be used in construing it.
            </p>
            <p>
              <u>b. Entire Agreement: </u> This Agreement, including any Service
              Order(s), certificate, schedule, exhibit or other document
              delivered pursuant to its terms, constitutes the entire agreement
              between the parties and supersedes any other agreement, whether
              oral or written, with respect to the subject matter hereof. There
              are no verbal agreements, representations, warranties,
              undertakings or agreements between the parties, and this Agreement
              may not be amended or modified in any respect, except by a written
              instrument signed by the parties to this Agreement. ANY
              WARRANTIES, TERMS, AND/OR CONDITIONS IN ANY PURCHASE AGREEMENTS,
              INVOICES, CREDIT APPLICATIONS, PURCHASE ORDERS, AND THE LIKE, OR
              ANY OTHER DOCUMENTS BETWEEN THE COMPANY AND User THAT CONFLICT
              WITH THE TERMS AND CONDITIONS SET FORTH HEREIN ARE GOVERNED BY THE
              TERMS HEREIN. The Company may at any time revise the terms of this
              Agreement by updating these terms and by providing notice to User
              of that change.
            </p>
            <p>
              <u>c. Force Majeure: </u> Neither party will be responsible nor in
              any way liable for any delays or failures in performance, except
              for payment of the Service Fee under this Agreement, arising out
              of or relating to a failure by the other party to perform any of
              its obligations under this Agreement, if such failure is caused by
              events or circumstances beyond its reasonable control, including,
              without limitation, acts of God, war, labor strike, terrorist act,
              fire, flood, earthquake, landslide, hurricane, typhoon, tsunami,
              volcanic eruption, inclement weather, health epidemic or any law,
              order, regulation, seizure or other action of any governing
              authority or agency. Notwithstanding the foregoing, in the event
              of such an occurrence, each party agrees to make a good faith
              effort to perform its obligations hereunder (“Force Majeure
              Event”).
            </p>
            <p>
              <u>d. Governing Law:</u> This Agreement and all claims arising out
              of or related to this Agreement are governed by and construed in
              accordance with the laws of the State of Wyoming without giving
              effect to any choice or conflict of law provision or rule that
              would cause the application of the laws of any jurisdiction other
              than the State of Wyoming.
            </p>
            <p>
              <u>e. Injunctive Relief:</u> User and the Company acknowledge that
              a breach of any of obligations set forth in Section 10 of this
              Agreement will render irreparable harm to the other party, and
              that a remedy at law for breach of the Agreement is inadequate,
              and that the harmed party shall therefore be entitled to seek any
              and all equitable relief, including, but not limited to, temporary
              and permanent injunctive relief, without the necessity of posting
              a bond, and to any other remedy that may be available under any
              applicable law or agreement between the parties. User and the
              Company acknowledge and agree that both damages and injunctive
              relief shall be proper modes of relief and are not to be
              considered as alternative remedies.
            </p>
            <p>
              <u>f. No Assignment: </u> User will not and may not assign or
              otherwise transfer this Agreement or any of the User’s rights and
              obligations under this Agreement, without the prior written
              consent of the Company, which shall not unreasonably be withheld.
              Any assignment or transfer in violation of this Section 14 (f)
              will be void. The Company may assign this Agreement without the
              User’s consent (i) in connection with a merger, acquisition or
              sale of all or substantially all of the Company’s assets, or (ii)
              to any affiliate or as part of a corporate reorganization, and
              effective upon such assignment, the assignee is deemed substituted
              for the Company as a party to this Agreement and the Company is
              fully released from all of its obligations and duties to perform
              under this Agreement. Subject to the foregoing, this Agreement
              will be binding upon, and inure to the benefit of the parties and
              their respective permitted successors and assigns. The User may
              not merge this Agreement with any other agreements with the
              Company it may be party to.
            </p>
            <p>
              <u>g. Notice:</u> Notice is effective when received. All notices,
              requests, demands and other communications under this Agreement
              must be in writing and will be deemed duly given, unless otherwise
              expressly indicated to the contrary in this Agreement, (i) when
              personally delivered, (ii) upon receipt of a telephonic facsimile
              transmission with a confirmed telephonic transmission answer back,
              (iii) three (3) days after having been deposited in the United
              States mail, certified or registered, return receipt requested,
              postage prepaid, (iv) one (1) business day after having been
              dispatched by a nationally recognized overnight courier service,
              or (v) on the date transmitted if by email, addressed to the
              parties or their permitted assigns at such address or number as is
              given in writing by either party to the other.
            </p>
            <p>
              <u>h. Relationship of the Parties:</u> Nothing in this Agreement
              shall be deemed to create an agency, employment, partnership,
              fiduciary or joint venture relationship between the parties.
              Neither party has the power or authority as agent, employee or in
              any other capacity to represent, act for, bind or otherwise create
              or assume any obligation on behalf of the other party for any
              purpose whatsoever without the other’s prior written consent.
            </p>
            <p>
              <u>i. Survival:</u> Any provision of this Agreement, which, by its
              nature, would survive termination or expiration of this Agreement,
              will survive any such termination or expiration, including,
              without limitation, those provisions concerning confidentiality,
              indemnification, and limitation of liability. In the event of the
              Company’s insolvency, cessation of operations, or filing for
              bankruptcy, the Company shall make good faith efforts, as directed
              by User, to either secure transition of User’s Service to the
              applicable Facility or return the User Hardware to the User at
              User’s sole expense.
            </p>
            <p>
              <u>j. Severability:</u>The unenforceability, invalidity, or
              illegality of any provision of this Agreement shall not render the
              other provisions unenforceable, invalid, or illegal.
            </p>
          </TermsSubtitleContainer>
          <CheckboxContainer>
            <CheckboxContent>
              <div>
                <input
                  type="checkbox"
                  checked={termsandConditionsData.checked}
                  onChange={termsandConditionsData.handleHeaderCheckboxToggle}
                />
              </div>
            </CheckboxContent>
            <ChecboxTextContainer>
              I Agree to terms and conditions
            </ChecboxTextContainer>
          </CheckboxContainer>
        </TermsContainer>
      </ModalContent>
    </ModalContainer>
  )
}

export default Modal
